### PR TITLE
spec: new upstream version 3.0.1

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by dustymabe** [comment]
once we move this into dist-git we wouldn't need to add the source tarball (rust-coreos-metadata-3.0.1-vendor.tar.xz) directly into git, right ?

LGTM

**Comment by lucab** [comment]
@dustymabe I think so, depending on releng/packaging policy (which is why I'm keeping a copy here and one remotely, in case). That's only vendoring though, there is also the actual source tarball on crates.io.

**Comment by dustymabe** [comment]
yeah. for the dist-git repos I think we have a policy against storing archives of source (we use the lookaside cache for that). so when we get the package into fedora then we'll just start over with the git history with the current version of the spec file from this repo probably. Does that sound right? 

This PR LGTM so feel free to merge!

**Comment by lucab** [comment]
@dustymabe clearer now, thanks. Spec for fedora will likely look very different due to using rust-packaging macros and unbundling the vendor tarball into proper rpm dependencies.

**Comment by lucab** [comment]
Built: https://copr.fedorainfracloud.org/coprs/lucab/rhcos-coreos-metadata/build/811793/

**Pull request merged**
